// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSoCYWTED2Cw1mdCz2886_vxAkMqG-Aq8',
    appId: '1:774454734912:web:69c647167bf589dc8befa5',
    messagingSenderId: '774454734912',
    projectId: 'flash-chat-af3fa',
    authDomain: 'flash-chat-af3fa.firebaseapp.com',
    storageBucket: 'flash-chat-af3fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmO1CGtAAJnNBYXhrUS9qJKNZCPfCFonI',
    appId: '1:774454734912:android:2f20af20be125b968befa5',
    messagingSenderId: '774454734912',
    projectId: 'flash-chat-af3fa',
    storageBucket: 'flash-chat-af3fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUOThkkE1ZRYzYqr6OMPBdlb-6wo38MKM',
    appId: '1:774454734912:ios:1dbcae54a14f45d68befa5',
    messagingSenderId: '774454734912',
    projectId: 'flash-chat-af3fa',
    storageBucket: 'flash-chat-af3fa.appspot.com',
    iosClientId: '774454734912-5vpldp9f35skoglcbnppakfh2npvdh7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUOThkkE1ZRYzYqr6OMPBdlb-6wo38MKM',
    appId: '1:774454734912:ios:1dbcae54a14f45d68befa5',
    messagingSenderId: '774454734912',
    projectId: 'flash-chat-af3fa',
    storageBucket: 'flash-chat-af3fa.appspot.com',
    iosClientId: '774454734912-5vpldp9f35skoglcbnppakfh2npvdh7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
